Inventory:
  size: 54
  title: "&8&n每日在线奖励"
Items:
  head:
    type: PLAYER_HEAD
    amount: 1
    data: 0
    custom-data: 0
    name: "&a个人信息"
    lore:
      - " "
      - " &e今日在线: &f%onlinereward_day%分钟 "
      - " &e总在线: &f%onlinereward_all%分钟 "
      - " "
    slot: 49
  fg:
    type: BLACK_STAINED_GLASS_PANE
    amount: 1
    data: 15
    name: "&f"
    lore: [ ]
    slots: 0-9,17,18,26,27,35,36,44-48,50-53
  30f:
    type: DRAGON_BREATH
    data: 0
    amount: 3
    name: "&a30分钟"
    lore:
      - " "
      - " &b奖励列表:"
      - " &f ◈ 精灵球 x32 "
      - " &f ◈ 金币 x1000 "
      - " &f ◈ 钻石 x10 "
      - " &f ◈ &e飞行能量 x100 "
      - " "
      - " &a点击领取该奖励&f(%status%&f) "
      - " "
    slot: 20
    reward: "example-30"
  60f:
    type: DRAGON_BREATH
    data: 0
    amount: 6
    name: "&a60分钟"
    lore:
      - " "
      - " &b奖励列表:"
      - " &f ◈ 精灵球 x32 "
      - " &f ◈ 金币 x2000 "
      - " &f ◈ 钻石 x20 "
      - " &f ◈ &e飞行能量 x200 "
      - " "
      - " &a点击领取该奖励&f(%status%&f) "
      - " "
    slot: 22
    reward: "example-60"
  90f:
    type: DRAGON_BREATH
    data: 0
    amount: 9
    name: "&a90分钟"
    lore:
      - " "
      - " &b奖励列表:"
      - " &f ◈ 精灵球 x32 "
      - " &f ◈ 金币 x3000 "
      - " &f ◈ 钻石 x30 "
      - " &f ◈ &e飞行能量 x300 "
      - " "
      - " &a点击领取该奖励&f(%status%&f) "
      - " "
    slot: 24
    reward: "example-90"
  120f:
    type: DRAGON_BREATH
    data: 0
    amount: 12
    name: "&a120分钟"
    lore:
      - " "
      - " &b奖励列表:"
      - " &f ◈ 精灵球 x32 "
      - " &f ◈ 金币 x4000 "
      - " &f ◈ 钻石 x40 "
      - " &f ◈ &e飞行能量 x500 "
      - " "
      - " &a点击领取该奖励&f(%status%&f) "
      - " "
    slot: 29
    reward: "example-120"
  150f:
    type: DRAGON_BREATH
    data: 0
    amount: 15
    name: "&a150分钟"
    lore:
      - " "
      - " &b奖励列表:"
      - " &f ◈ 精灵球 x32 "
      - " &f ◈ 金币 x5000 "
      - " &f ◈ 钻石 x50 "
      - " &f ◈ &b体力药丸&f(小) x1 "
      - " &f ◈ &e飞行能量 x700 "
      - " "
      - " &a点击领取该奖励&f(%status%&f) "
      - " "
    slot: 31
    reward: "example-150"
  180f:
    type: DRAGON_BREATH
    data: 0
    amount: 18
    name: "&a180分钟"
    lore:
      - " "
      - " &b奖励列表:"
      - " &f ◈ 精灵球 x32 "
      - " &f ◈ 金币 x6000 "
      - " &f ◈ 钻石 x60 "
      - " &f ◈ &6体力药丸&f(大) x1 "
      - " &f ◈ &d补签卡 x1 "
      - " &f ◈ &e飞行能量 x1000 "
      - " "
      - " &a点击领取该奖励&f(%status%&f) "
      - " "
    slot: 33
    reward: "example-180"