name: OnlineReward
main: com.blank038.onlinereward.OnlineReward
version: ${version}
api-version: 1.13
folia-supported: true
depend:
  - AyCore
  - NBTAPI
softdepend:
  - PlaceholderAPI
commands:
  or:
    descrption: Command for OnlineReward